"""Export this season's per-player-game stats and model features to a browsable CSV.

The raw nflverse pulls live in data/raw/ (gitignored, ~155 MB, regenerated by pull_data.py).
This writes props_log/features_<season>.csv: one row per player-game for QB/RB/WR/TE with the
actual stats, the pre-game rolling features the model uses (usage, efficiency, Next Gen / PFR
stats, injuries, QB-specific usage, role, opponent defense, game environment) and the opponent.

    python scripts/export_stats.py            # current season
    python scripts/export_stats.py 2025
"""
import sys
from pathlib import Path

import polars as pl

sys.path.insert(0, str(Path(__file__).resolve().parent))
import props  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
COLS = [
    "season", "week", "game_id", "team", "opponent_team", "player_display_name", "position", "role",
    # actuals
    "attempts", "passing_yards", "carries", "rushing_yards", "targets", "receptions", "receiving_yards",
    "target_share", "carry_share", "offense_pct",
    # game environment (pre-game)
    "implied_total", "team_spread", "indoor", "wind", "e_team_plays", "e_team_pass_rate",
    # rolling usage / efficiency (pre-game, exponentially weighted, half-life 4 games)
    "e_attempts", "e_passing_yards", "e_yds_per_att", "e_passing_epa",
    "e_carries", "e_rushing_yards", "e_carry_share", "e_yds_per_car",
    "e_targets", "e_receptions", "e_receiving_yards", "e_target_share", "e_air_yards_share", "e_yds_per_tgt",
    "e_offense_pct", "n_prior",
    # injuries: own report, teammates out by position, opponent units out, redistributed volume
    "own_q", "own_dnp", "own_out", "team_inj_wr", "team_inj_rb", "team_inj_te", "opp_inj_db", "opp_inj_front",
    "vac_car", "vac_tgt", "car_mult", "tgt_mult", "e_carries_adj", "e_targets_adj",
    # usage with the expected starting QB
    "expected_qb", "e_target_share_qb", "e_targets_qb", "e_receiving_yards_qb", "n_qb",
    # Next Gen / PFR / expected yards (rolling)
    "e_ngs_sep", "e_ngs_cushion", "e_ngs_iay", "e_ngs_yac_oe", "e_ngs_catch_pct",
    "e_ngs_eff", "e_ngs_8box", "e_ngs_ryoe_att", "e_ngs_ttt", "e_ngs_agg", "e_ngs_cpoe", "e_ngs_ays",
    "e_pfr_drop_pct", "e_pfr_rec_bt", "e_pfr_ybc", "e_pfr_yac_c", "e_pfr_rush_bt", "e_pfr_pressure_pct",
    "e_ff_rec_yds_exp", "e_ff_rush_yds_exp", "e_ff_pass_yds_exp", "e_ff_rec_yoe", "e_ff_rush_yoe",
    # opponent defense (rolling, pre-game)
    "opp_pass_yds_alw", "opp_rb_rush_alw", "opp_wr_rec_alw", "opp_te_rec_alw", "opp_rb_rec_alw",
    "opp_adj_def_pass", "opp_adj_def_run", "opp_role_alw", "opp_role_ratio",
    "opp_rec_yoe_alw", "opp_rush_yoe_alw", "opp_pass_yoe_alw", "opp_man_rate_prev",
]


def main():
    season = int(sys.argv[1]) if len(sys.argv) > 1 else None
    df = props.build()
    season = season or df["season"].max()
    out = (df.filter(pl.col("season") == season).select([c for c in COLS if c in df.columns])
           .sort("week", "team", "position", "player_display_name"))
    path = ROOT / "props_log" / f"features_{season}.csv"
    out.write_csv(path, float_precision=3)
    print(f"wrote {path.relative_to(ROOT)}: {out.height} player-games, {out.width} columns")


if __name__ == "__main__":
    main()
